name: Control
author: Jo Colina <jo@jocolina.com>
description: Runs a Control flow configuration

runs:
  using: docker
  image: Dockerfile

inputs:
  config:
    description: Configuration file for Control
    required: true

  global:
    description: Run Control CLI from globally installed module (your project does not need Control as a dependency)
    required: false
    default: false

  install_control:
    description: Override to install Control dependency manually anyways
    required: false
    default: false
